### ISSUE TITLE
add support for code action icons

### ISSUE THREAD

**Issue by prabirshrestha** [mattn/vim-lsp-icons#3]
https://github.com/prabirshrestha/vim-lsp/pull/1085

This is equivalent to vscode light bulb. We might want to change hint to be some other icon and instead show code actions as bulb instead.

**Comment by mattn** [comment]
I'm trying to show the hint icon but still not.

```
  let g:lsp_document_code_action_signs_enabled = 1
  let g:lsp_document_code_action_signs_hint    = {
  \ 'icon': s:icons_dir . 'hint' . s:icon_ext,
  \}
  let g:lsp_document_code_action_signs_priority = 10
```

What is wrong?

**Comment by prabirshrestha** [comment]
This is working for me.

```
let g:lsp_document_code_action_signs_hint  = {'text': '?', 'icon': s:icons_dir . 'hint'        . s:icon_ext}
```

First trying checking if `:LspCodeAction` returns something. typescript language server always seems to return `organize imports` so you might want to try that instead.

![image](https://user-images.githubusercontent.com/287744/110249774-9b8e1280-7f2c-11eb-9a3b-4d26aaa837ce.png)

**Comment by mattn** [comment]
Added. Thank you.

https://github.com/mattn/vim-lsp-icons/commit/409a0008d017a412166dbede92ca85f53b6903e2
